name: Validate pull request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Run commitlint
        uses: lw-ci/action-conventional-pull-request@v3
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config_file: "./.github/config/commitlint.js"

      - name: Add comment if there are errors
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.valid == 'false')
        with:
          header: pr-title-lint-error
          message: |
            ⚠️ Pull request title validation failed!

            Titles must follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and include a scope.

            ```
            ${{ steps.lint_pr_title.outputs.report }}
            ```

      - name: Delete comment if there are no errors
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.lint_pr_title.outputs.valid == 'true' }}
        with:
          header: pr-title-lint-error
          delete: true
